# This is a wrapper function for interplot

#' Plot Interaction Effects
#'
#' @description Drawing interaction plot. This function is a wrapper for \code{\link[interplot]{interplot}} function.
#'
#' @param m	A model object including an interaction term, or, alternately, a data frame generated by an earlier call to interplot using the argument \code{plot = FALSE}.
#' @param v1 The name (as a string) of the variable of interest in the interaction term; its conditional coefficient estimates will be plotted.
#' @param v2 The name (as a string) of the other variable in the interaction term
#' @param plot A logical value indicating whether the output is a plot or a dataframe including the conditional coefficient estimates of \code{var1}, their upper and lower bounds, and the corresponding values of var2.
#' @param steps	Desired length of the sequence. A non-negative number, which for seq and seq.int will be rounded up if fractional. The default is 100 or the unique categories in the \code{var2} (when it is less than 100. Also see unique).
#' @param ci A numeric value defining the confidence intervals. The default value is 95\% (0.95).
#' @param hist A logical value indicating if there is a histogram of 'var2' added at the bottom of the conditional effect plot.
#' @param var2_dt	A numerical value indicating the frequency distibution of 'var2'. It is only used when 'hist == TRUE'. When the object is a model, the default is the distribution of 'var2' of the model.
#' @param point	A logical value determining the format of plot. By default, the function produces a line plot when var2 takes on ten or more distinct values and a point (dot-and-whisker) plot otherwise; option TRUE forces a point plot.
#' @param sims Number of independent simulation draws used to calculate upper and lower bounds of coefficient estimates: lower values run faster; higher values produce smoother curves.
#' @param xmin A numerical value indicating the minimum value shown of x shown in the graph. Rarely used.
#' @param xmax A numerical value indicating the maximum value shown of x shown in the graph. Rarely used.
#' @param ercolor A character value indicating the outline color of the whisker or ribbon.
#' @param esize	A numerical value indicating the size of the whisker or ribbon.
#' @param ralpha A numerical value indicating the transparency of the ribbon.
#' @param rfill	A character value indicating the filling color of the ribbon.
#'
#' @return \code{ggplot} object (axis and theme settings can be added later).
#'
#' @importFrom interplot interplot
#'
#' @export
plot_interact <- function(
  m, v1, v2, plot = TRUE, steps = NULL, ci = 0.95,
  hist = FALSE, var2_dt = NA, point = FALSE, sims = 5000, xmin = NA,
  xmax = NA, ercolor = NA, esize = 0.5, ralpha = 0.5,
  rfill = "grey70"
  ) {

p <- interplot(m=m, var1=v1, var2=v2, plot = plot, steps = steps, ci = ci,
hist = hist, var2_dt = var2_dt, point = point, sims = sims, xmin = xmin,
xmax = xmax, ercolor = ercolor, esize = esize, ralpha = ralpha,
rfill = rfill) + estvis.theme()

return(p)

}
